In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 7.6 MB/s eta 0:00:00
Downloading alembic-1.18.5-py3-none-any.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.7/264.7 kB 9.7 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.18.5 colorlog-6.12.0 optuna-4.9.0

In [2]:
# Import necessary libraries

import optuna

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source.

import pandas as pd

# Load the Pima Indian Diabetes Dataset (from UCI repository)

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

columns = [
    'Pregnancies',
    'Glucose',
    'BloodPressure',
    'SkinThickness',
    'Insulin',
    'BMI',
    'DiabetesPedigreeFunction',
    'Age',
    'Outcome'
]

# Load the dataset

df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = [
    'Glucose',
    'BloodPressure',
    'SkinThickness',
    'Insulin',
    'BMI'
]

df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)

X = df.drop('Outcome', axis=1)
y = df['Outcome']


# Split data into training and test sets (70% train, 30% test)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)


# Optional: Scale the data for better model performance

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# Check the shape of the data

print(f"Training set shape: {X_train.shape}")
print(f"Test set shape: {X_test.shape}")

Training set shape: (537, 8)
Test set shape: (231, 8)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):

    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=3,
        scoring='accuracy'
    ).mean()

    # Return the accuracy score for Optuna to maximize
    return score


# Create a study object and optimize the objective function
study = optuna.create_study(
    direction='maximize',
    sampler=optuna.samplers.TPESampler()
)

# Run 50 trials to find the best hyperparameters
study.optimize(objective, n_trials=50)

[I 2026-07-30 15:58:02,573] A new study created in memory with name: no-name-2817b951-b2b9-4f61-b27f-24a5e4d216ca
[I 2026-07-30 15:58:04,177] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 113, 'max_depth': 7}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:05,606] Trial 1 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 5}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:06,814] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 89, 'max_depth': 12}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:09,836] Trial 3 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 152, 'max_depth': 11}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:10,772] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 124, 'max_depth': 8}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:11,083] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 55, 'max_depth': 4}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:12,085] Trial 6 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 159, 'max_depth': 8}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:13,228] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 182, 'max_depth': 19}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:13,805] Trial 8 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 93, 'max_depth': 8}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:14,870] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 174, 'max_depth': 13}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:16,132] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 20}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 15:58:16,892] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 112, 'max_depth': 19}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-07-30 15:58:17,634] Trial 12 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 115, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:18,311] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 102, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:18,807] Trial 14 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 72, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:19,225] Trial 15 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 64, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:19,618] Trial 16 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 58, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:20,146] Trial 17 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:21,352] Trial 18 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 128, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:22,107] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 74, 'max_depth': 11}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:23,475] Trial 20 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 132, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:24,396] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:25,138] Trial 22 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 113, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:26,113] Trial 23 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 146, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:27,200] Trial 24 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:27,770] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:28,456] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 20}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:29,263] Trial 27 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 126, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:29,689] Trial 28 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 64, 'max_depth': 13}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:30,394] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 113, 'max_depth': 10}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:31,026] Trial 30 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 103, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:31,883] Trial 31 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:32,747] Trial 32 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 135, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:33,675] Trial 33 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 140, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:35,104] Trial 34 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:36,381] Trial 35 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 121, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:37,383] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 119, 'max_depth': 12}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:38,407] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 159, 'max_depth': 19}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:39,295] Trial 38 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 140, 'max_depth': 13}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:39,876] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 92, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:40,417] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 83, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:41,246] Trial 41 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:42,070] Trial 42 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 126, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:42,745] Trial 43 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 107, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:43,440] Trial 44 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 117, 'max_depth': 3}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:44,419] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 155, 'max_depth': 19}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:45,044] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 97, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:46,287] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 181, 'max_depth': 20}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:47,254] Trial 48 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 144, 'max_depth': 6}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-07-30 15:58:48,675] Trial 49 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 135, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):

    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score

In [11]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())

study.optimize(objective, n_trials=60)

[I 2026-07-30 16:06:09,628] A new study created in memory with name: no-name-ae35ce89-2fef-4f3b-b1ae-66ba3f2dd6c5
[I 2026-07-30 16:06:12,081] Trial 0 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 66, 'max_depth': 15}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-07-30 16:06:16,101] Trial 1 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 133, 'max_depth': 18}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:21,536] Trial 2 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 197, 'max_depth': 3}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:22,683] Trial 3 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 18}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:26,599] Trial 4 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 187, 'max_depth': 17}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:28,047] Trial 5 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 96, 'max_depth': 15}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:29,325] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 123, 'max_depth': 13}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:29,804] Trial 7 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 83, 'max_depth': 4}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:30,891] Trial 8 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 178, 'max_depth': 18}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:31,719] Trial 9 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 15}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:32,643] Trial 10 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 151, 'max_depth': 9}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:33,511] Trial 11 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 20}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:34,271] Trial 12 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 121, 'max_depth': 11}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:35,244] Trial 13 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 157, 'max_depth': 8}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:35,918] Trial 14 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 107, 'max_depth': 20}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:36,598] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 20}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:37,244] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 20}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:38,777] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 157, 'max_depth': 17}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:39,570] Trial 18 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 79, 'max_depth': 13}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:40,636] Trial 19 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 113, 'max_depth': 18}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:41,569] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 13}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:42,306] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 116, 'max_depth': 18}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:43,039] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 116, 'max_depth': 17}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:44,113] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 169, 'max_depth': 18}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:44,664] Trial 24 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 86, 'max_depth': 16}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:45,486] Trial 25 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 19}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:46,191] Trial 26 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 111, 'max_depth': 16}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:47,077] Trial 27 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 141, 'max_depth': 14}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:47,675] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 95, 'max_depth': 19}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:48,043] Trial 29 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 54, 'max_depth': 16}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-07-30 16:06:48,547] Trial 30 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 70, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:49,022] Trial 31 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 71, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:49,461] Trial 32 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 65, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:49,922] Trial 33 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 72, 'max_depth': 17}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:50,259] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:50,850] Trial 35 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 72, 'max_depth': 15}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:51,796] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 92, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:52,362] Trial 37 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 16}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:53,107] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 76, 'max_depth': 17}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:54,635] Trial 39 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 197, 'max_depth': 14}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:55,035] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 63, 'max_depth': 14}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:55,476] Trial 41 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 66, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:55,862] Trial 42 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:56,415] Trial 43 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:56,844] Trial 44 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 71, 'max_depth': 5}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:57,689] Trial 45 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:58,259] Trial 46 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 89, 'max_depth': 20}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:58,891] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 99, 'max_depth': 17}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:06:59,697] Trial 48 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 125, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:00,504] Trial 49 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 129, 'max_depth': 15}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:01,293] Trial 50 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 124, 'max_depth': 20}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:02,264] Trial 51 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 151, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:03,154] Trial 52 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 139, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:03,699] Trial 53 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:04,679] Trial 54 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 112, 'max_depth': 17}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:06,479] Trial 55 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 186, 'max_depth': 20}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:07,572] Trial 56 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 126, 'max_depth': 16}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:08,395] Trial 57 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 15}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:09,438] Trial 58 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 164, 'max_depth': 16}. Best is trial 30 with value: 0.7802607076350094.
[I 2026-07-30 16:07:10,349] Trial 59 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 11}. Best is trial 30 with value: 0.7802607076350094.

In [13]:
# print the best result
print(f'Best Trial Accuracy: {study.best_trial.value}')
print(f'best hyper parameter: {study.best_trial.params}')

Best Trial Accuracy: 0.7802607076350094
best hyper parameter: {'n_estimators': 70, 'max_depth': 18}

In [14]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [15]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())

study.optimize(objective, n_trials=50)

[I 2026-07-30 16:15:44,365] A new study created in memory with name: no-name-62a38227-d48e-4d76-9b3a-7165ffe1346c
[I 2026-07-30 16:15:47,981] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 180, 'max_depth': 17}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 16:15:53,612] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 195, 'max_depth': 14}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 16:15:58,587] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 188, 'max_depth': 14}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-30 16:16:01,881] Trial 3 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 185, 'max_depth': 16}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:03,380] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 68, 'max_depth': 13}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:04,839] Trial 5 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 130, 'max_depth': 3}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:06,488] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 175, 'max_depth': 15}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:07,073] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 20}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:08,525] Trial 8 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 152, 'max_depth': 13}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:09,509] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 14}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:10,439] Trial 10 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 134, 'max_depth': 17}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:11,362] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 151, 'max_depth': 12}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:12,534] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 189, 'max_depth': 13}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:13,416] Trial 13 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 15}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:14,398] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 160, 'max_depth': 13}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:15,298] Trial 15 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 161, 'max_depth': 4}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:16,235] Trial 16 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 155, 'max_depth': 8}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:17,309] Trial 17 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 173, 'max_depth': 9}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:17,635] Trial 18 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 50, 'max_depth': 12}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:18,726] Trial 19 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 195, 'max_depth': 4}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:20,001] Trial 20 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 19}. Best is trial 3 with value: 0.7765363128491619.
[I 2026-07-30 16:16:20,857] Trial 21 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 19}. Best is trial 21 with value: 0.7765363128491621.
[I 2026-07-30 16:16:21,686] Trial 22 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 88, 'max_depth': 8}. Best is trial 21 with value: 0.7765363128491621.
[I 2026-07-30 16:16:22,585] Trial 23 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 91, 'max_depth': 13}. Best is trial 21 with value: 0.7765363128491621.
[I 2026-07-30 16:16:23,537] Trial 24 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 118, 'max_depth': 17}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:24,554] Trial 25 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 165, 'max_depth': 19}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:25,509] Trial 26 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 162, 'max_depth': 7}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:26,081] Trial 27 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 97, 'max_depth': 8}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:26,509] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 61, 'max_depth': 18}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:26,881] Trial 29 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 66, 'max_depth': 4}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:27,364] Trial 30 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 80, 'max_depth': 4}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:28,073] Trial 31 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 128, 'max_depth': 5}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:28,799] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 117, 'max_depth': 13}. Best is trial 24 with value: 0.7783985102420856.
[I 2026-07-30 16:16:29,228] Trial 33 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 69, 'max_depth': 18}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:30,110] Trial 34 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 145, 'max_depth': 12}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:30,876] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 123, 'max_depth': 13}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:31,312] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 69, 'max_depth': 16}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:31,954] Trial 37 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 109, 'max_depth': 6}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:32,580] Trial 38 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 94, 'max_depth': 17}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:33,270] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 8}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:33,997] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 71, 'max_depth': 15}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:35,100] Trial 41 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 125, 'max_depth': 4}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:36,413] Trial 42 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 20}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:37,551] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 186, 'max_depth': 14}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:37,945] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 58, 'max_depth': 10}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:38,529] Trial 45 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 91, 'max_depth': 10}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:39,229] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 109, 'max_depth': 14}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:40,437] Trial 47 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 199, 'max_depth': 15}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:41,449] Trial 48 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 177, 'max_depth': 5}. Best is trial 33 with value: 0.7783985102420857.
[I 2026-07-30 16:16:42,315] Trial 49 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 137, 'max_depth': 14}. Best is trial 33 with value: 0.7783985102420857.

# Visualization

In [17]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [18]:
# 1. Optimization History
plot_optimization_history(study).show()

In [19]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [20]:
# slice plot

plot_slice(study).show()

In [21]:
# countour plot

plot_contour(study).show()

In [22]:
# plto param

plot_param_importances(study).show()

In [23]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [24]:
# Define the objective function for Optuna
def objective(trial):

    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical(
        'classifier',
        ['SVM', 'RandomForest', 'GradientBoosting']
    )

    if classifier_name == 'SVM':

        # SVM hyperparameters
        C = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical(
            'kernel',
            ['linear', 'rbf', 'poly', 'sigmoid']
        )
        gamma = trial.suggest_categorical(
            'gamma',
            ['scale', 'auto']
        )

        model = SVC(
            C=C,
            kernel=kernel,
            gamma=gamma,
            random_state=42
        )

    elif classifier_name == 'RandomForest':

        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':

        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=3,
        scoring='accuracy'
    ).mean()

    return score

In [25]:
study = optuna.create_study(direction='maximize')

study.optimize(objective, n_trials=100)

[I 2026-07-30 16:42:08,282] A new study created in memory with name: no-name-d622b94b-ebdc-409e-af86-a30795d3559a
[I 2026-07-30 16:42:10,519] Trial 0 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 184, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-07-30 16:42:13,599] Trial 1 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 135, 'learning_rate': 0.10733551529460444, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-07-30 16:42:13,670] Trial 2 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.9172313963086588, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:17,990] Trial 3 finished with value: 0.7448789571694601 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 234, 'learning_rate': 0.03677196120469833, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:19,107] Trial 4 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 177, 'learning_rate': 0.08354178899545696, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:24,868] Trial 5 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 222, 'learning_rate': 0.08118150846392173, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:26,405] Trial 6 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 278, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:29,377] Trial 7 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 258, 'learning_rate': 0.019104413702607, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:29,411] Trial 8 finished with value: 0.6945996275605214 and parameters: {'classifier': 'SVM', 'C': 20.168198611631414, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:31,540] Trial 9 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 95, 'learning_rate': 0.017814803666098788, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:31,585] Trial 10 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.2030314201940113, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:33,967] Trial 11 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 292, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:34,589] Trial 12 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 56, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-07-30 16:42:34,645] Trial 13 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12797651035308985, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:34,701] Trial 14 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15995054714214585, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:34,757] Trial 15 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11741618651986019, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:34,816] Trial 16 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10200577518242444, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:34,881] Trial 17 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.0082667923206727, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:34,945] Trial 18 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 0.6758375684967617, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:35,010] Trial 19 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.39620023248233394, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:35,099] Trial 20 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.7429672726656555, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:35,153] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10376517934590232, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:35,212] Trial 22 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24418309255068263, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:35,263] Trial 23 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11280543600259371, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:35,324] Trial 24 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 0.3447010231935555, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:35,409] Trial 25 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.10116544570792142, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:35,964] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 87.09888304647532, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,006] Trial 27 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.42593034652095774, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,061] Trial 28 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.27197677018312, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,390] Trial 29 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,444] Trial 30 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.2225875914888551, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,485] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17441959059260215, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,521] Trial 32 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16089177248234904, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,556] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15844925699151993, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,592] Trial 34 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4178256490089184, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:36,629] Trial 35 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 0.11159994892700259, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:37,338] Trial 36 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 125, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:39,952] Trial 37 finished with value: 0.7448789571694601 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 181, 'learning_rate': 0.24087696787790686, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:39,996] Trial 38 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 0.26480104360630535, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:40,588] Trial 39 finished with value: 0.7411545623836125 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 91, 'learning_rate': 0.29565644503839006, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:40,627] Trial 40 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5661816996346669, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:40,660] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10740716204399012, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:40,691] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1582598519658715, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:40,721] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10068562823602327, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:40,752] Trial 44 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2148432775719423, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:41,513] Trial 45 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 146, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:46,585] Trial 46 finished with value: 0.7225325884543762 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 217, 'learning_rate': 0.010805114471949555, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:46,651] Trial 47 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.16659228023982933, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:46,701] Trial 48 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2817971134059196, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:46,761] Trial 49 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 1.2605502967785678, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:47,612] Trial 50 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 91, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:47,669] Trial 51 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10082252357525832, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:47,725] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14539080942645288, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:47,781] Trial 53 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1686383016011307, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:47,830] Trial 54 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1502591191784282, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:47,901] Trial 55 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.27740688251222634, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:47,960] Trial 56 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13564084937627743, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,070] Trial 57 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 262, 'learning_rate': 0.04283182553563657, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,111] Trial 58 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1436696723165479, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,150] Trial 59 finished with value: 0.7411545623836128 and parameters: {'classifier': 'SVM', 'C': 0.571098107600613, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,187] Trial 60 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3318683825043965, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,224] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14444003364508165, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,263] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14327915761773155, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,302] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2247228814460764, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,351] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13144934648061513, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,390] Trial 65 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2056176456304332, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,435] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12917484559272852, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,504] Trial 67 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.559219287143007, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,551] Trial 68 finished with value: 0.7579143389199254 and parameters: {'classifier': 'SVM', 'C': 0.34660169433667626, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:55,584] Trial 69 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2126204826030974, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:56,412] Trial 70 finished with value: 0.7802607076350093 and parameters: {'classifier': 'RandomForest', 'n_estimators': 155, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:56,451] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13313814566954937, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:56,487] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13699587236495, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:56,523] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1918767524112581, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:56,562] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12589579600305317, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:56,601] Trial 75 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.183495608445832, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:56,639] Trial 76 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.28555389117421026, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:59,863] Trial 77 finished with value: 0.7262569832402234 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 204, 'learning_rate': 0.151219056702945, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:59,913] Trial 78 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13359690392581447, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:42:59,963] Trial 79 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24493795101916252, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-07-30 16:43:00,029] Trial 80 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.10064047140758155, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.

In [26]:
# Retrieve the best trial
best_trial = study.best_trial

print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.12797651035308985, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [27]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.765363,2026-07-30 16:42:08.292982,2026-07-30 16:42:10.519228,0 days 00:00:02.226246,NaN,False,RandomForest,NaN,NaN,NaN,13.0,1.0,3.0,184.0,COMPLETE
1,1,0.739292,2026-07-30 16:42:10.522829,2026-07-30 16:42:13.599791,0 days 00:00:03.076962,NaN,NaN,GradientBoosting,NaN,NaN,0.107336,11.0,10.0,2.0,135.0,COMPLETE
2,2,0.774674,2026-07-30 16:42:13.602549,2026-07-30 16:42:13.670091,0 days 00:00:00.067542,0.917231,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.744879,2026-07-30 16:42:13.672158,2026-07-30 16:42:17.990486,0 days 00:00:04.318328,NaN,NaN,GradientBoosting,NaN,NaN,0.036772,16.0,9.0,9.0,234.0,COMPLETE
4,4,0.765363,2026-07-30 16:42:17.991726,2026-07-30 16:42:19.107489,0 days 00:00:01.115763,NaN,NaN,GradientBoosting,NaN,NaN,0.083542,3.0,7.0,4.0,177.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.787709,2026-07-30 16:43:06.002086,2026-07-30 16:43:06.037816,0 days 00:00:00.035730,0.100512,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.715084,2026-07-30 16:43:06.039244,2026-07-30 16:43:06.074916,0 days 00:00:00.035672,0.157254,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.789572,2026-07-30 16:43:06.076258,2026-07-30 16:43:06.115232,0 days 00:00:00.038974,0.121819,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.785847,2026-07-30 16:43:06.116542,2026-07-30 16:43:06.157901,0 days 00:00:00.041359,0.231839,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.759777,2026-07-30 16:43:06.159171,2026-07-30 16:43:06.202140,0 days 00:00:00.042969,0.182207,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE

# ye chcek karna ke har algo kitni bar run hua

In [28]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 78
GradientBoosting    12
RandomForest        10
Name: count, dtype: int64

In [29]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.741310
RandomForest        0.766480
SVM                 0.776918
Name: value, dtype: float64